### ISSUE TITLE
Sample doc URL doesn't work the same way on Knative as Cloud Run

### ISSUE THREAD

**Issue by ahmetb** [as-a-service/pdf#1]
https://pdf-2wvlk7vg3a-uc.a.run.app/?url=http://homepages.inf.ed.ac.uk/neilb/TestWordDoc.doc works fine:

![image](https://user-images.githubusercontent.com/159209/57811502-43ff3100-771f-11e9-9558-3e058b9f0f52.png)

But when I invoke the version I deployed to Cloud Run on GKE, it doesn't work 
http://pdf.default.example.com/?url=http://homepages.inf.ed.ac.uk/neilb/TestWordDoc.doc

I get an empty page:

![image](https://user-images.githubusercontent.com/159209/57811535-55e0d400-771f-11e9-9d2d-440ff1b6b72b.png)

but it's not actually a server error:

```
curl http://pdf.default.example.com/\?url\=http://homepages.inf.ed.ac.uk/neilb/TestWordDoc.doc
%PDF-1.5
%äüöß
2 0 obj
<</Length 3 0 R/Filter/FlateDecode>>
stream
x�3�3T(�*T0P0�30�P034Գ47T0���E�\�Z
y\�
��
endstream
endobj

3 0 obj
45
endobj

5 0 obj
<<
>>
endobj

6 0 obj
<</Font 5 0 R
/ProcSet[/PDF/Text]
>>
endobj

1 0 obj
<</Type/Page/Parent 4 0 R/Resources 6 0 R/MediaBox[0 0 612 792]/Group<</S/Transparency/CS/DeviceRGB/I true>>/Contents 2 0 R>>
endobj

4 0 obj
<</Type/Pages
/Resources 6 0 R
/MediaBox[ 0 0 612 792 ]
/Kids[ 1 0 R ]
/Count 1>>
endobj

7 0 obj
<</Type/Catalog/Pages 4 0 R
/OpenAction[1 0 R /XYZ null null 0]
/Lang(en-US)
>>
endobj

8 0 obj
<</Creator<FEFF005700720069007400650072>
/Producer<FEFF004C0069006200720065004F0066006600690063006500200036002E0031>
/CreationDate(D:20190515213924Z')>>
endobj

xref
0 9
0000000000 65535 f
0000000229 00000 n
0000000019 00000 n
0000000135 00000 n
0000000371 00000 n
0000000154 00000 n
0000000176 00000 n
0000000469 00000 n
0000000565 00000 n
trailer
<</Size 9/Root 7 0 R
/Info 8 0 R
/ID [ <0AF8104DC200CA4C216E59422AA741C3>
<0AF8104DC200CA4C216E59422AA741C3> ]
/DocChecksum /0B81FAC93AE551B036C955E3985BF321
>>
startxref
734
%%EOF
```

Similarly when I deploy it to IBM KS, it works fine.
http://pdf.default.knative-cluster.sjc04.containers.appdomain.cloud/?url=http://homepages.inf.ed.ac.uk/neilb/TestWordDoc.doc

![image](https://user-images.githubusercontent.com/159209/57811646-a5270480-771f-11e9-8019-9f946c5d435c.png)

What is this black magic?

**Comment by ahmetb** [comment]
I'm suspecting CR on GKE cluster doesn't have the outbound network connectivity enabled. In that case, I don't expect to get an empty PDF, this should be a HTTP 500.

**Comment by steren** [comment]
Yes, this is likely due to outbound networking not being configured properly.

**Comment by steren** [comment]
I agree that we should return a 500 if we cannot download the file

**Comment by ahmetb** [comment]
Not a problem anymore since outbound network is enabled by default on CR-GKE.
